services:
  #nginx
  web:
    image: nginx:1.25.1-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  #php  
  app: 
    build: 
      dockerfile: ./php/Dockerfile
      target: app_dev 
      #target app_dev which will build app and app_dev stage from corresponding docker file (Can also use a different build by 
      # setting an environment variable )
    volumes:
      - ./app:/var/www/html
      - ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
    environment:
      MYSQL_HOST: db # service name which should be db.
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      REDIS_HOST: cache # service name which maps to redis.
      REDIS_PORT: ${REDIS_PORT}
      # See https://xdebug.org/docs/all_settings#mode
      XDEBUG_MODE: "${XDEBUG_MODE:-off}" # If no environment variable of XDEBUG_MODE is set, default to false.
    
    extra_hosts:
      # Ensure that host.docker.internal is correctly defined on linux
      - host.docker.internal:host-gateway


  #mysql
  db:
    image: mysql:8.0
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - 3306:3306
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
  
  #redis
  cache:
    image: redis:7.0.11-alpine

volumes:
  mysqldata: