name: CI
on:
    push:
        branches:
            - "*"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Intall composer dependencies
              working-directory: ./app
              run: composer install
            - name: Run tests
              working-directory: ./app
              run: composer run-test
